helm:
  parameters:
  - name: containers.image
    value: 548844171305.dkr.ecr.us-east-1.amazonaws.com/private-example
    forcestring: true
  - name: containers.tag
    value: v0.4.17
    forcestring: true
