helm:
  parameters:
  - name: container.image.repository
    value: 548844171305.dkr.ecr.us-east-1.amazonaws.com/private-example
    forcestring: true
  - name: container.image.tag
    value: v0.4.13
    forcestring: true
