helm:
  parameters:
  - name: image.repository
    value: 548844171305.dkr.ecr.us-east-1.amazonaws.com/private-example
    forcestring: true
  - name: image.tag
    value: v0.4.14
    forcestring: true
