myingress: 
 enabled: false
replicaCount: 1

containers:
  image: 548844171305.dkr.ecr.us-east-2.amazonaws.com/dimple-app
  tag: latest

ports:
  container_port: 8085
  lb_port: 80

items:
- serviceName: simple-app
  prefix: /
- serviceName: user-app
  prefix: /api/v2/user/
- serviceName: ride-app
  prefix: /api/v2/ride/

host: api.velvioo.brainscale.cloud
