apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy  # Define the name of the Deployment
  labels:
    type: deployment    #Label to identify this resource as a deployment
spec: 
  replicas: {{ .Values.replicaCount }} # Number of replicas to maintain for the application
  selector:
    matchLabels:
      application: {{ .Release.Name }}-hostname 
  template:
    metadata:
      labels:
        application: {{ .Release.Name }}-hostname 
    spec:
      containers:
      - name: {{ .Release.Name }}-hostname-print
        image: "{{ .Values.containers.image }}:{{ .Values.containers.tag }}" # Define the image for the container
        ports:
        - containerPort: {{ .Values.ports.container_port }}  # Port exposed within the container for the application
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
        
