{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-cpu-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}-deploy
  minReplicaCount: {{ .Values.minReplicaCount }}  # We don't want pods if the queue is empty
  maxReplicaCount: {{ .Values.maxReplicaCount }}  # We don'ts want to have more than 5 replicas
  pollingInterval: {{ .Values.pollingInterval }}  # How frequently we should go for metrics (in seconds)
  cooldownPeriod:  {{ .Values.cooldownPeriod }}  # How many seconds should we wait for downscale     
  triggers:
  - type: cpu
    metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
    metadata:
      value: {{ .Values.cpuValue }}
{{- end }}
